name = "Development Configuration"
uuid = "development"

[account]
username = "test"

[logger]
path = "log/"
level = "DEBUG"
format = "[%(levelname)s] - %(asctime)s: %(message)s"
format_pid = "[%(levelname)s] - %(asctime)s - %(process)d: %(message)s"

[general]
sleep_time = 1

[auction]
pool_size = 3

[server]
pool_size = 3

[communication] # general communication settings
buffer_size = 1024
timeout = 1
reliable_timeout = 1
reliable_retries = 3

[communication.multicast.discovery]
group = "224.1.1.1"
port = 7707
ttl = 32

[communication.multicast.auction]
group_base = "224.2.0.0/16" # this is the base prefix for the multicast group
port = 7708
ttl = 32

[communication.multicast.auction.announcement]
port = 7709
period_base = 5.0
period_hf = 1.0

[communication.multicast.auction.peers]
port = 7710

[communication.multicast.auction.state]
port = 7711

[communication.multicast.auction.bid]
port = 7712

[communication.replica] # settings for the communication between replicas
timeout = 5

[communication.replica.replication] # settings for the replication of the auction information
period = 1
timeout = 5 # timeout for the replication manager to wait for a response from the replicas

[communication.replica.heartbeat]
period = 10

[communication.replica.election]
ports = [7713, 7714, 7715]
timeout = 5

[communication.header]
reliable-req = "RELIABLE_REQUEST"
reliable-res = "RELIABLE_RESPONSE"
reliable-multicast = "RELIABLE_MULTICAST"

[communication.header.isis]
isis-message = "ISIS_MESSAGE"
proposed-seq = "PROPOSED_SEQ"
agreed-seq = "AGREED_SEQ"

[communication.header.replica]
find-req = "FIND_REPLICA_REQUEST"
find-res = "FIND_REPLICA_RESPONSE"

[communication.header.heartbeat]
req = "HEARTBEAT_REQUEST"
res = "HEARTBEAT_RESPONSE"

[communication.header.election]
req = "ELECTION_REQUEST"
ans = "ELECTION_ANSWER"
coordinator = "ELECTION_COORDINATOR"

[communication.header.auction]
announcement = "AUCTION_ANNOUNCEMENT"
information-replication = "AUCTION_INFORMATION_REPLICATION"
peers-announcement = "PEERS_ANNOUNCEMENT"
state-announcement = "AUCTION_STATE_ANNOUNCEMENT"
bid = "AUCTION_BID"
