name = "Development Configuration"

[logger]
path = "log/"
level = "DEBUG"
format = "[%(levelname)s] - %(asctime)s: %(message)s"

[server.replica]
local_pool_size = 5
auction_pool_size = 5

[communication.multicast.discovery]
group = "224.1.1.1"
port = 5007
ttl = 32

[communication.multicast.auction]
group_prefix = "224.2."
initial_port = 5008

[communication.unicast]
port = 5006

[communication.header.replica]
find-replica-req = "FIND_REPLICA_REQUEST"
find-replica-res = "FIND_REPLICA_RESPONSE"
find-replica-ack = "FIND_REPLICA_ACK"

[communication.header.auction]
auction-announcement = "AUCTION_ANNOUNCEMENT"
auction-information-req = "AUCTION_INFORMATION_REQUEST"
auction-information-res = "AUCTION_INFORMATION_RESPONSE"
auction-bid = "AUCTION_BID"
auction-win = "AUCTION_WIN"

[communication.header.heartbeat]
heartbeat-request = "HEARTBEAT_REQUEST"
heartbeat-response = "HEARTBEAT_RESPONSE"

[communication.header.election]
election-request = "ELECTION_REQUEST"
election-response = "ELECTION_RESPONSE"
