name = "Development Configuration"
uuid = "development"

[account]
username = "test"


[logger]
path = "log/"
level = "DEBUG"
format = "[%(levelname)s] - %(asctime)s: %(message)s"
format_pid = "[%(levelname)s] - %(asctime)s - %(process)d: %(message)s"

[general]
sleep_time = 0.5

[server.replica]
local_pool_size = 5
auction_pool_size = 1

[communication]
buffer_size = 1024
timeout_receive = 1
timeout_response = 5
reliable_timeout = 1
reliable_attempts = 5


[communication.replica]
emitter_period = 1
timeout = 5

[communication.heartbeat]
timeout = 1

[communication.election]
timeout = 5
port = 5555

[communication.total_ordering_isis]
timeout = 5

[communication.multicast.discovery]
group = "224.1.1.1"
port = 5007
ttl = 32

[communication.multicast.auction]
group_base = "224.2.0.0/16" # this is the base prefix for the multicast group
port = 5008
ttl = 32
announcement_period = 5.0
high_frequency_announcement_period = 1.0

[communication.header]
reliable-req = "RELIABLE_REQUEST"
reliable-res = "RELIABLE_RESPONSE"
reliable-multicast = "RELIABLE_MULTICAST"

[communication.header.replica]
find-replica-req = "FIND_REPLICA_REQUEST"
find-replica-res = "FIND_REPLICA_RESPONSE"
peers-announcement = "PEERS_ANNOUNCEMENT"

[communication.header.auction]
auction-announcement = "AUCTION_ANNOUNCEMENT"
auction-state-announcement = "AUCTION_STATE_ANNOUNCEMENT"
auction-information-replication = "AUCTION_INFORMATION_REPLICATION"
auction-bid = "AUCTION_BID"
auction-win = "AUCTION_WIN"

[communication.header.heartbeat]
heartbeat-req = "HEARTBEAT_REQUEST"
heartbeat-res = "HEARTBEAT_RESPONSE"

[communication.header.election]
election-req = "ELECTION_REQUEST"
election-ans = "ELECTION_ANSWER"
election-coordinator = "ELECTION_COORDINATOR"

[communication.header.total_ordering_isis]
isis-message = "ISIS_MESSAGE"
proposed-seq = "PROPOSED_SEQ"
agreed-seq = "AGREED_SEQ"