name = "Development Configuration"

[logger]
path = "log/"
level = "DEBUG"
format = "[%(levelname)s] - %(asctime)s: %(message)s"

[multicast.discovery]
group = "224.1.1.1"
port = "5007"
ttl = 32

[message]
find-replica-request = "FIND_REPLICA_REQUEST"
