name = "Development Configuration"
uuid = "development"

[account]
username = "test"


[logger]
path = "log/"
level = "DEBUG"
format = "[%(levelname)s] - %(asctime)s: %(message)s"

[general]
sleep_time = 0.5

[server.replica]
local_pool_size = 5
auction_pool_size = 1

[communication]
buffer_size = 1024
timeout_receive = 1
timeout_response = 20

[communication.replica]
emitter_period = 2
timeout = 20

[communication.heartbeat]
timeout = 5

[communication.election]
timeout = 5

[communication.multicast.discovery]
group = "224.1.1.1"
port = 5007
ttl = 32

[communication.multicast.auction]
group_base = "224.2.0.0/16" # this is the base prefix for the multicast group
port = 5008
ttl = 32

[communication.unicast]
port = 5006

[communication.header.replica]
find-replica-req = "FIND_REPLICA_REQUEST"
find-replica-res = "FIND_REPLICA_RESPONSE"
find-replica-ack = "FIND_REPLICA_ACK"
replica-announcement = "REPLICA_ANNOUNCEMENT"

[communication.header.auction]
auction-announcement = "AUCTION_ANNOUNCEMENT"
auction-information-req = "AUCTION_INFORMATION_REQUEST"
auction-information-res = "AUCTION_INFORMATION_RESPONSE"
auction-information-ack = "AUCTION_INFORMATION_ACK"
auction-bid = "AUCTION_BID"
auction-win = "AUCTION_WIN"

[communication.header.heartbeat]
heartbeat-req = "HEARTBEAT_REQUEST"
heartbeat-res = "HEARTBEAT_RESPONSE"

[communication.header.election]
reelection-announcement = "REELECTION_ANNOUNCEMENT"
election-req = "ELECTION_REQUEST"
election-res = "ELECTION_RESPONSE"
